apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geth
  namespace: argocd
spec:
  project: ethereum-nodes
  source:
    repoURL: 'git@github.com:haroldsphinx/linkpool-eth.git'
    targetRevision: main
    path: k8s/ethereum-node/holesky/geth-execution
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: geth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 