apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geth
  namespace: argocd
spec:
  project: ethereum-nodes
  source:
    repoURL: 'git@github.com:haroldsphinx/ethereum-helm-charts.git'
    targetRevision: main
    path: charts/geth
    helm:
      releaseName: geth
      valueFiles:
        - geth-testnet.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: geth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 