apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  url: Z2l0QGdpdGh1Yi5jb206YmxvY2tvcHMlLmdpdA==
  sshPrivateKey: ${SSH_PRIVATE_KEY}