apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lighthouse-consensus
  namespace: argocd
spec:
  project: ethereum-nodes
  source:
    repoURL: 'git@github.com:haroldsphinx/ethereum-helm-charts.git'
    targetRevision: main
    path: charts/lighthouse
    helm:
      releaseName: lighthouse
      valueFiles:
        - lighthouse-testnet.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lighthouse-consensus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 