apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ethereum-nodes
  namespace: argocd
spec:
  description: Ethereum nodes
  sourceRepos:
    - 'git@github.com:haroldsphinx/linkpool-eth.git'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
   - name: read-only
      policies:
        - p, proj:ethereum-nodes:read-only, applications, get, */*, allow
      description: Read-only access to applications
   - name: admin
      policies:
        - p, proj:ethereum-nodes:admin, applications, get, */*, allow
      description: Admin access to applications
