---
loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
        heartbeat_period: 1s
        heartbeat_timeout: 1m
    chunk_idle_period: 1h
    chunk_retain_period: 1h
    
  storageConfig:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: s3
    filesystem:
      directory: /data/loki/chunks
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h 
  compactor:
    retention_enabled: true 
    delete_request_store: filesystem
  ruler:
  enable_api: true
  storage:
    type: filesystem
    filesystem:
      directory: /data/loki/ruler

  querier:
    max_concurrent: 4

  storage:
    type: filesystem
    filesystem:
      directory: /data/loki/storage

persistence:
  enabled: true
  storageClass: standard
  size: 5Gi
  accessModes:
    - ReadWriteOnce

service:
  type: ClusterIP
  port: 3100
