loki:
  auth_enabled: false
  
  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem
    filesystem:
      directory: /var/loki/data



  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

  storageConfig:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      shared_store: s3
      cache_ttl: 24h

  limits_config:
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
    max_query_series: 10000
    max_query_lookback: 744h
    max_query_length: 721h
    max_streams_per_user: 10000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 744h

  chunk_store_config:
    max_look_back_period: 744h

  table_manager:
    retention_deletes_enabled: true
    retention_period: 744h

backend:
  replicas: 1
  persistence:
    size: 10Gi
    
read:
  replicas: 1
  persistence:
    size: 10Gi

write:
  replicas: 1
  persistence:
    size: 10Gi

monitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false

