---
controller:
  replicaCount: 2
  service:
    type: NodePort
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
      prometheus.io/path: "/metrics"
    nodePorts:
      http: 30080
      https: 30443
    externalTrafficPolicy: Local
  admissionWebhooks:
    enabled: false
  metrics:
    enabled: true
defaultBackend:
  enabled: true

